### ISSUE TITLE
字典中的映射关系

### ISSUE THREAD

**Issue by morphr5466** [chenchenzi/P2FA_Mandarin_py3#5]
您好，感谢您的分享。
请问字典中的汉字，和它后面类似拼音的一种标注格式（我不知道怎么称呼这种格式）是如何对应的呢？从哪里可以找到它们之间的关系？

**Comment by chenchenzi** [comment]
我一般是通过观察同音字的标注来给新加入的字标注。

**Comment by morphr5466** [comment]
感谢您的回复！为了方便，我整理了一份拼音到标注的对应关系，不一定完整:)

**Comment by morphr5466** [comment]
[result_order.txt](https://github.com/chenchenzi/P2FA_Mandarin_py3/files/5741049/result_order.txt)

**Comment by chenchenzi** [comment]
@morphr5466 如果是IPA和标注的关系的话，P2FA 英文的用的是ARPAbet。中文那个好像有一些改动。

**Comment by morphr5466** [comment]
原来是这样，非常感谢您的解答！这对我帮助很大。
